test cm

diff --git a/argocd/cert-manager/base/openshift-gitops-job-create-cluster-cert-manager-resources.yaml b/argocd/cert-manager/base/openshift-gitops-job-create-cluster-cert-manager-resources.yaml
--- a/argocd/cert-manager/base/openshift-gitops-job-create-cluster-cert-manager-resources.yaml
+++ b/argocd/cert-manager/base/openshift-gitops-job-create-cluster-cert-manager-resources.yaml
@@ -40,14 +40,16 @@ spec:
                   --for condition=cert-manager-webhook-deploymentAvailable \
                   --timeout=60s || true # Ignore timeout error to continue the loop
                 # Check if CertManager is degraded
-                degraded_count=$(oc get certmanager cluster -o yaml | yq '[.status.conditions[] | select(.type | endswith("Degraded") and .status == "True")] | length')
-                if [ $degraded_count -eq 0 ]; then
+                degraded_count=$(echo "$certmanager_yaml" | yq e '[.status.conditions[] | select(.type | test("Degraded$") and .status == "True")] | length' - 2>/dev/null || echo "error")
+                if [ "$degraded_count" == "error" ]; then
+                  echo "Error parsing CertManager status. YAML content:"
+                  echo "$certmanager_yaml"
+                  echo "Retrying after deletion."
+                elif [ "$degraded_count" -eq 0 ]; then
                   echo "CertManager is not degraded and all conditions are met. Proceeding."
                   break
                 else
                   echo "CertManager is degraded (degraded conditions: $degraded_count). Deleting and retrying."
-                  oc delete certmanager cluster --ignore-not-found
-                  echo "CertManager 'cluster' CR deleted."
                 fi
               done
 
